---
game: "301"
# checkin: double-in
checkout: straight-out
players:
  - name: Player 1
  - name: Player 2
  - name: Player 3

statistics:
  enabled: true
  path: darts-counter-test.db

logging:
  enabled: true
  level: info
  path: darts-counter.log
